[graph]
all-features = true
targets = [
	"x86_64-unknown-linux-gnu",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-msvc",
]

[advisories]
version = 2
ignore = []

[licenses]
version = 2
confidence-threshold = 0.9
allow = [
	"MIT",              # https://spdx.org/licenses/MIT
	"Apache-2.0",       # https://spdx.org/licenses/Apache-2.0
	"Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016
]

[licenses.private]
ignore = false

[bans]
multiple-versions = "allow"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
