name: Audit

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "30 12 * * 5"

env:
  SIMPLE_PROTOCOLS_LOG: debug
  SIMPLE_PROTOCOLS_LOG_STYLE: always
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  audit:
    name: Regular Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - run: cargo deny check
        if: success() || failure()
      - uses: actions/dependency-review-action@v2
        if: (success() || failure()) && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        with:
          fail-on-severity: low
