name: Audit

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "30 12 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Regular Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-outdated
      - uses: EmbarkStudios/cargo-deny-action@v1
        if: success() || failure()
      - uses: actions/dependency-review-action@v2
        if: (success() || failure()) && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        with:
          fail-on-severity: low
      - run: cargo outdated --root-deps-only --exit-code 1
        if: success() || failure()
